Replicas on same node
derailed/popeye pull request #149
Opened 2021-01-11 16:48 UTC by marians

Closes https://github.com/derailed/popeye/issues/143

This PR implements a check that issues a warning if all replicas of a deployment are scheduled to the same host.

Preview:

![image](https://user-images.githubusercontent.com/273727/104212086-1ce98d00-5435-11eb-8ccd-abdddc1bf90b.png)

2021-01-11 16:53 UTC, marians commented
Question: should this check also be done for StatefulSets?

2021-01-12 16:13 UTC, pipo02mix commented
In my opinion, it makes sense to include statefulsets

2021-01-12 23:14 UTC, derailed commented
@marians @pipo02mix Thank you both for this report! Yes probably more importantly so with sts imho.

2021-02-26 13:14 UTC, marians commented
@derailed Just added support for StatefulSets. I'd welcome a review.

2021-05-04 23:39 UTC, derailed requested changes

2021-05-04 23:39 UTC, derailed commented on internal/sanitize/sts.go
> +	if *st.Spec.Replicas <= 1 {
@marians Check nil?

2021-05-04 23:39 UTC, derailed commented on internal/sanitize/sts.go
> +	nodeMap := make(map[string]int)
Don't think we need to count here ie if the node is already in the map the pods are collocated
```go
s.ListPodsBySelector(st.Namespace, st.Spec.Selector
make(map[string]struct{}, len(oo))
if _, ok := nodeMap[pod.Spec.NodeName]; ok {
   s.AddCode(...)
   return
```

That said I don't think these are valid general checks ie ES multiple shards can land on the same node? Thus that would raise a false positive??

2023-05-30 09:24 UTC, marians commented
Closing, as I'm not working on this any more.

2023-05-30 09:24 UTC, closed without merging