fix: ignore PodSecurityPolicies in Kubernetes > 1.25
derailed/popeye pull request #239
Opened 2022-12-24 18:44 UTC by jon4hz

Hi, this PR disables scanning for PodSecurityPolicies in Kubernetes > 1.25.

Closes #236

2023-01-12 16:50 UTC, mrhein commented
LGTM

@derailed could you bundle a new release?

2023-01-12 17:53 UTC, jon4hz commented
Not sure why the test fails. I didn't make any changes to `go.mod`. Should I run `go mod tidy` to see if there are any changes?  
 Even though, it isn't really related to the PR.

2023-01-12 18:31 UTC, derailed commented
@jon4hz Do the tests pass locally for you? I think deps changed and hence go mod tidy should fix this issue. If not I'll take another look. Tx!!

2023-01-12 21:03 UTC, jon4hz commented
It is a bit weird. The tests are all passing locally and `go mod tidy` doesn't trigger any change. However I noticed, that the test pipeline is still using go 1.16. Bumping this to go 1.18 might fix the issue.

2023-01-18 10:45 UTC, deric commented
@derailed Any progress on this?

2023-01-25 18:13 UTC, diego95root commented
It'd be great if this could be merged :)

2023-02-10 10:24 UTC, muhlba91 commented
is there any progress?
we upgraded a few weeks ago and this blocks us to enable all automated scans we had in place before 1.25.

2023-02-16 06:25 UTC, derailed requested changes
@jon4hz Awesome! Thank you for this! 
Could you rebase your branch from master to resolve the conflicts?

2023-02-20 16:53 UTC, derailed commented
Closing - Issue addressed in v0.11.1

2023-02-20 16:53 UTC, closed without merging